backend:
  name: git-gateway
  repo: https://github.com/Avneesh0404/FitWithUs
  branch: main  # Change this to your repo's main branch

media_folder: "Img"  # Upload images to your "Img" folder
public_folder: "/Img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Welcome Text", name: "welcome_text", widget: "text" }
